import { NextRequest, NextResponse } from 'next/server'
import { createClient as createServiceClient } from '@supabase/supabase-js'
import { createClient } from '@/lib/supabase/server'

const supabaseAdmin = createServiceClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

interface StudentRow {
  full_name: string
  class: string
  parent_name?: string
  parent_phone: string
}

export async function POST(req: NextRequest) {
  // Verify caller is an admin
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ message: 'Unauthorized' }, { status: 401 })

  const { students, school_id } = await req.json()

  if (!school_id || !Array.isArray(students) || students.length === 0) {
    return NextResponse.json({ message: 'school_id and students array required' }, { status: 400 })
  }

  if (students.length > 500) {
    return NextResponse.json({ message: 'Maximum 500 students per bulk import' }, { status: 400 })
  }

  // Verify caller is admin for this school
  const { data: callerProfile } = await supabase
    .from('user_profiles')
    .select('school_id, role')
    .eq('user_id', user.id)
    .single()

  if (!callerProfile || callerProfile.role !== 'admin' || callerProfile.school_id !== school_id) {
    return NextResponse.json({ message: 'Forbidden' }, { status: 403 })
  }

  // Plan limit check
  const { data: school } = await supabaseAdmin
    .from('schools')
    .select('max_students')
    .eq('id', school_id)
    .single()

  const { count: currentCount } = await supabaseAdmin
    .from('students')
    .select('id', { count: 'exact', head: true })
    .eq('school_id', school_id)
    .eq('is_active', true)

  if (school && ((currentCount ?? 0) + students.length) > school.max_students) {
    return NextResponse.json({
      message: `Adding ${students.length} students would exceed your plan limit of ${school.max_students}. Currently have ${currentCount ?? 0}.`
    }, { status: 403 })
  }

  // Validate each row
  const errors: string[] = []
  const phoneRegex = /^(0|\+?234)[789][01]\d{8}$/

  students.forEach((s: StudentRow, i: number) => {
    if (!s.full_name?.trim()) errors.push(`Row ${i + 1}: full_name is required`)
    if (!s.class?.trim()) errors.push(`Row ${i + 1}: class is required`)
    if (!s.parent_phone?.trim()) errors.push(`Row ${i + 1}: parent_phone is required`)
    else if (!phoneRegex.test(s.parent_phone.replace(/\s/g, ''))) {
      errors.push(`Row ${i + 1}: invalid phone "${s.parent_phone}"`)
    }
  })

  if (errors.length > 0) {
    return NextResponse.json({ message: 'Validation errors', errors }, { status: 422 })
  }

  // Bulk insert — qr_code auto-generated by DB trigger
  const rows = students.map((s: StudentRow) => ({
    school_id,
    full_name: s.full_name.trim(),
    class: s.class.trim(),
    parent_name: s.parent_name?.trim() || null,
    parent_phone: s.parent_phone.trim(),
  }))

  const { data: inserted, error } = await supabaseAdmin
    .from('students')
    .insert(rows)
    .select('id, full_name, class, qr_code, parent_phone')

  if (error) {
    return NextResponse.json({ message: error.message }, { status: 500 })
  }

  return NextResponse.json({ success: true, count: inserted?.length ?? 0, students: inserted })
}